### ISSUE TITLE
ACplugin update 11/7

### ISSUE THREAD

**Issue by RillaDikted** [smallest-cock/Custom-Ball-Online#1]
alphaconsole update 11/7 breaks everything LOL.  is this something you will be able to update?

**Comment by smallest-cock** [comment]
@RillaDikted  Yeah the new update changed the structure of the json files and other stuff like naming patterns used for console variables... which broke the functionality of this plugin. But it shouldn't be too hard to update, I just need to redo how some stuff works like reading the json files and getting texture names.

**Comment by RillaDikted** [comment]
I just want to say THANK YOU!!!  My esports org and I love this so much.  It looks soo good when we cast games on our Twitch <3
![Nebula_Esports_Ball](https://github.com/user-attachments/assets/3d554bc4-b862-4249-84a0-b5e8ce25afd6)
