### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by Kirby-alt** [smallest-cock/Custom-Ball-Online#2]
I extract the file and try to install it and for days it wont let me download it. I'm not to sure why.

**Comment by smallest-cock** [comment]
You seem to have fixed it.. I assume it was because RL was open when you ran `install.bat`, which caused an error when the script was trying to overwrite the old `CustomBallOnline.dll` because it was in still in use. I added a note in the install steps to clarify that RL needs to be closed 👌
